@startuml
class Pirata{
    items
    ebriedad
    dinero

    esUtilPara(unaMision)
    tiene(unItem)
    seAnimaASaquear(unObjetivo)
    estaPasadoDeGrogXD()
    dinero() 
    ebriedad()
    cantidadItems()
    puedeFormarParteDeUnaTripulacion(unBarco)
    incorporarseATripulacion(unBarco)
    tomarTragoDeGrogXD()
    aumentarEbriedad(unaCantidad)
    gastarDinero(unaCantidad)
    esEspiaDeLaCorona()
}

class Barco{
    tripulantes 
    mision
    capacidad

    temible()
    tripulacionSuficiente()
    tripulantes()
    alguienTieneLlaveDeCofre()
    barcoPasadoDeGrogXD()
    tieneLugarParaUnoMas()
    agregarPirataATripulacion(unPirata)
    cambiarMision(unaMision)
    pirataMasEbrio()
    anclar()
    hacerTomarALosTripulantes()
    perderPirata()
    tripulantesEspiasDeLaCorona()
    cantidadTripulantesPasadosDeGrogXD()
    tripulantesPasadosDeGrogXD()
    tripulantePasadoDeGrogXDConMasDinero()
}

class Mision{
    tripulanteUtilParaMision(unTripulante)
    barcoUtilParaMision(unBarco)
}

class BusquedaDelTesoro extends Mision{
    tripulanteUtilParaMision(unTripulante)
    barcoUtilParaMision(unBarco)
}

class ConvertirseEnLeyenda extends Mision{
    itemObligatorio
    tripulanteUtilParaMision(unTripulante)
    barcoUtilParaMision(unBarco)
}

class Saqueo extends Mision{
    objetivo
    dinerioNecesario

    objetivo()
    tripulanteUtilParaMision(unTripulante)
    barcoUtilParaMision(unBarco)

}

interface tipoVictima{
    objetivo
}

class BarcoPirata{
    tripulantes

    tripulantes()
    esVulnearableA(unBarco)
}

class CiudadCostera{
    habitantes
    esVulnearableA(unBarco)
}

Saqueo .up.|> tipoVictima
BarcoPirata ..|> tipoVictima
CiudadCostera ..|> tipoVictima
Barco -right-> "*" Pirata
Barco --> Mision

@enduml